INSERT INTO orders (member_id, name, price, completed)
SELECT
        FLOOR(RAND() * 1000) + 1 AS member_id,
    CONCAT('Order ', @curRow := @curRow + 1) AS name,
        FLOOR(RAND() * 10000) + 1 AS price,
    ROUND(RAND()) AS completed
FROM
    (SELECT @curRow := 0) r
        JOIN
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1
        JOIN
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2
LIMIT 100;
